project:
  type: website
  output-dir: docs

website:
  title: "Evangelia Karakoliou" # Musicians' Health" 
  navbar:
    left:
      - href: index.qmd
        text: Home
      - media.qmd
      - performance_experience.qmd
      - music_industry.qmd
      - publications.qmd
      - streaming.qmd
    tools:
      - icon: linkedin
        href: https://linkedin.com/in/lia-88oo/
      - icon: github
        href: https://github.com/0r080r0
      - icon: twitch
        href: https://twitch.com/
      - icon: envelope
        href: "mailto:hakaiosan@gmail.com"
  search: false 
  page-footer:
    right: "Built with R and [Quarto](https://quarto.org/)"
    left: "Copyright &copy; 2024-2025 by Evangelia Karakoliou - Musician & Researcher"

# Define static assets (audio files, images & videos)
static-assets:
  - "img/"
  - "audio/"
  - "videos/"

# Adding a media section to site configuration
audio_files:
  - "audio/Flumine.wav"
  - "audio/ICD.wav"
  - "audio/Delirium.wav"
  - "audio/Intro.wav"
  - "audio/Dark.wav"
  - "audio/Shadow.wav"
  - "audio/ShadowOfTheSunAcoustic.wav"
  - "audio/CT.wav"
  - "audio/abduct.wav"

format:
  html:
    theme: solar
    css: styles.css      # Custom CSS for the page
    include-in-header:
      - text: |
          <style>
          html {
            scroll-behavior: smooth;
            overflow-y: scroll; /* Always show scrollbar */
          }
          </style>
    toc: true             # Table of contents
editor: source           # Set the editor to source mode
